config/routes.rb
Rails.application.routes.draw do

  resources :users, controller: "users" do
    resources :likes, controller: "likes"
    resources :posts, controller: "posts"
    resources :comments, controller: "comments"
  end

  resources :posts, controller: "posts" do
    resources :comments, controller: "comments", only: [:create, :new, :update, :destroy]
    resources :likes, controller: "likes"
    resources :buyings, controller: "buyings"
  end

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: 'logout'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/posts/payment/new" => "payment#new", as: "payment_new"
  post '/posts/payment/checkout' => "payment#checkout", as: "payment_checkout"
  root 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord
  require 'carrierwave/orm/activerecord'
  mount_uploader :avatar, AvatarUploader
  has_many :authentications, :dependent => :destroy

  has_secure_password

  validates_presence_of :fullname
  validates_presence_of :email
  validates :password, presence: true, length: { in: 6..20 }
  validates :valid_email, presence: true
  before_create :valid_email

  has_many :posts
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :buyings

  enum gender: [:not_specified, :male, :female]

  # def valid_password
  #   unless self.password.length >= 6
  #     errors.add(:password, "length is too short.")
  #   end
  # end

  def valid_email
    unless self.email =~ /\w+@\w+\.\w{2,}/
      errors.add(:email, "is not valid.")
    end
  end

  def self.create_with_auth_and_hash(authentication, auth_hash)
    create! do |user|
      user.fullname = auth_hash["extra"]["raw_info"]["name"]
      user.email = auth_hash["extra"]["raw_info"]["email"]
      user.authentications << (authentication)
      user.password = SecureRandom.hex(7)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [
      :sorted_by,
      :search_query,
    ]
  )

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/
      # Simple sort on the created_at column.
      # Make sure to include the table name to avoid ambiguous column names.
      # Joining on other tables is quite common in Filterrific, and almost
      # every ActiveRecord table has a 'created_at' column.
      order("users.created_at #{ direction }")
    when /^name_/
      # Simple sort on the name colums
      order("LOWER(users.last_name) #{ direction }, LOWER(users.first_name) #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  def self.options_for_sorted_by
    [
      ['Name (a-z)', 'name_asc'],
      ['Name (z-a)', 'name_desc'],
      ['Created at (desc)', 'created_at_desc'],
      ['Created at (asc)', 'created_at_asc'],
    ]
  end

  def name
    fullname
  end

  scope :search_query, -> (search) { where("LOWER(fullname) LIKE ?", "%#{search.downcase}%") }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update]

  def index
    @user = User.new
    # @posts = Post.all.order("created_at DESC")
    # @comment = Comment.new

    @filterrific = initialize_filterrific(User, params[:filterrific],
                                          select_options: {
                                            sorted_by: User.options_for_sorted_by
                                          },
                                          ) or return

    @users = @filterrific.find

    respond_to do |format|
      format.html
      format.js
    end
  end


  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User has been created"
      redirect_to login_path
    else
      flash.now[:danger] = "Invalid input"
      render :new
    end
  end

  def show
    @user_post = @user.posts.order("created_at DESC")
  end

  def edit
  end

  def update
    @user.update(update_params)
    if @user.save(validate: false)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      flash.now[:danger] = "Update failed"
      render :edit
    end
  end



  private

  def user_params
    params.require(:user).permit(:email, :fullname, :username, :password)
  end

  def update_params
    params.require(:user).permit(:email, :fullname, :username, :password, :website, :bio, :gender, :phone_num, :avatar)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit.html.erb
<%= form_for @user do |form| %>
  <div class = 'container'>
    <div class="form-group">
      <% if !@user.avatar? %>
        <%= image_tag @user.avatar, :class => "img-responsive img-circle" %>
      <% else %>
        <%= image_tag @user.avatar.thumb, class: "img-circle" %>
        <%= form.label :remove_avatar do %>
          <%= form.check_box :remove_avatar %>
          Remove
        <% end %>
      <% end %>
      <%= form.file_field :avatar %>
      <%= form.hidden_field :avatar_cache %>
    </div>
    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, type: 'email', class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :fullname %>
      <%= form.text_field :fullname, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :username %>
      <%= form.text_field :username, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :website %>
      <%= form.text_field :website, class: "form-control" %>
      <div>
        <div class="form-group">
          <%= form.label :bio %>
          <%= form.text_field :bio, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :phone_number %>
          <%= form.number_field :phone_num, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= select_tag 'user[gender]', options_for_select([["Not Specified", :not_specified], ["Male", :male],["Female", :female]]) %>
          <div>
            <div class="form-group">
              <%= form.label :password %>
              <%= form.password_field :password, class: "form-control" %>
            </div>
            <div class="submit-field">
              <%= form.submit "Submit", class: "btn btn-default"%>
            </div>
          <%end%>

app/views/users/_form.html.erb
<div class="form-group">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email', class: "form-control" %>
</div>
<div class="form-group">
  <%= form.label :fullname %>
  <%= form.text_field :fullname, class: "form-control" %>
</div>
<div class="form-group">
  <%= form.label :username %>
  <%= form.text_field :username, class: "form-control" %>
</div>
<div class="form-group">
  <%= form.label :password %>
  <%= form.password_field :password, class: "form-control" %>
</div>
<div class="submit-field">
  <%= form.submit "Submit", class: "btn btn-default"%>
</div>

app/views/users/_list.html.erb
<% @users.each do |user| %>
  <p><%= link_to (user.fullname), user_path(user) %></p>
<% end %>

app/views/users/edit.html.erb
<nav class="navbar">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand"><%= link_to "Rightnowagram", posts_path%></div>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.fullname %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= image_tag current_user.avatar.profile%></li>
            <li><%= link_to "Profile", user_path(current_user.id) %></li>
            <li><%= link_to "Search for Users", users_path%></li>
            <li><%= link_to "Log Out", logout_path%></li>
          </ul>
        </li>
      </ul>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</div>
<!-- /.container-fluid -->
</nav>
</div>
<h1>Editing User</h1>
<%= render '/users/edit' %>
<%= link_to 'Back', @user, class: "btn btn-default" %>

app/views/users/index.html.erb
<nav class="navbar">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand"><%= link_to "Rightnowagram", posts_path%></div>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.fullname %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= image_tag current_user.avatar.profile%></li>
            <li><%= link_to "Profile", user_path(current_user.id) %></li>
            <li><%= link_to "Search for Users", users_path%></li>
            <li><%= link_to "Log Out", logout_path%></li>
          </ul>
        </li>
      </ul>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</div>
<!-- /.container-fluid -->
</nav>
</div>
<p id="notice"><%= notice %></p>
<h1>Users</h1>
<div class = "col-sm-4"></div>
<div class = "col-sm-4">
  <% if current_user.nil? %>
    <%= form_for @user do |form|%>
      <%= render partial: 'users/form', object: form %>
    <%end%>
  <%else%>
    <form class="form-inline">
      <%= form_for_filterrific @filterrific do |f| %>
        <div>
          <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
          <%= f.text_field(:search_query, class: 'filterrific-periodically-observed form-control mb-2 mr-sm-2 mb-sm-0', placeholder: 'Search'
    ) %>
        </div>
        <div>
          <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by], class: 'form-control mb-2 mr-sm-2 mb-sm-0') %>
        </div>
        <div>
          <%= link_to(
      'Reset filters',
      reset_filterrific_url, class: 'form-control mb-2 mr-sm-2 mb-sm-0'
    ) %>
        </div>
        <%# add an automated spinner to your form when the list is refreshed %>
        <%= render_filterrific_spinner %>
      <% end %>
    </form>
    <br>
    <div class="row">
      <div id="filterrific_results">
        <%= render(partial: 'users/list', locals: { users: @users }) %>
      </div>
    </div>
  </div>
<%end%>
<div class = "col-sm-4"></div>

app/views/users/index.js.erb
<% js = escape_javascript(
  render(partial: 'users/list', locals: { users: @users })
) %>
  $("#filterrific_results").html("<%= js %>");

app/views/users/new.html.erb
<h1>New User</h1>
<div class = "text-center well">
  <%= form_for @user do |form|%>
    <%= render partial: '/users/form', object: form %>
  <%end%>
</div>
<%= link_to 'Back', root_path, class: "btn btn-default" %><%= link_to "Sign In", login_path, class: "btn btn-default" %>

app/views/users/show.html.erb
<nav class="navbar">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand"><%= link_to "Rightnowagram", posts_path%></div>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.fullname %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= image_tag current_user.avatar.profile%></li>
            <li><%= link_to "Profile", user_path(current_user.id) %></li>
            <li><%= link_to "Search for Users", users_path%></li>
            <li><%= link_to "Log Out", logout_path%></li>
          </ul>
        </li>
      </ul>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</div>
<!-- /.container-fluid -->
</nav>
</div>
<p id="notice"><%= notice %></p>
<div class = "col-sm-2"></div>
<div class = "col-sm-8">
  <div class = "user-details text-center">
    <div class = "avatar">
      <%= image_tag @user.avatar.thumb unless @user.avatar.blank?%>
    </div>
    <h4><%=@user.fullname%></h4>
    <b><%=@user.username unless @user.username.blank?%></b>
    <p>
      <%=@user.bio unless @user.bio.blank?%><br>
      <%=@user.website unless @user.website.blank?%><br>
    </p>
  </div>
  <div class= "text-center ">
    <% @user_post.each do |post|%>
      <%= link_to image_tag (post.images[0].display.url if post.images[0]) %><br>
      <hr>
    <%end%>
  </div>
  <div class = "col-sm-2">
    <%= button_to 'Edit', edit_user_path(@user), :method => :get, :class => "btn btn default" %><%= button_to 'Back', user_posts_path(current_user), :method => :get, :class => "btn btn default" %>
  </div>
</div>