config/routes.rb
Rails.application.routes.draw do

  resources :users, controller: "users" do
    resources :likes, controller: "likes"
    resources :posts, controller: "posts"
    resources :comments, controller: "comments"
  end

  resources :posts, controller: "posts" do
    resources :comments, controller: "comments", only: [:create, :new, :update, :destroy]
    resources :likes, controller: "likes"
    resources :buyings, controller: "buyings"
  end

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: 'logout'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/posts/payment/new" => "payment#new", as: "payment_new"
  post '/posts/payment/checkout' => "payment#checkout", as: "payment_checkout"
  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<nav class="navbar">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Rightnowagram</a>
      <form class="navbar-form navbar-left">
      </form>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign Up/Sign In<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Sign Up", new_user_path %></li>
            <li><%= link_to "Sign in with Facebook", "/auth/facebook" %></li>
            <li><%= link_to "Sign In", login_path %></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>
</div>
<div class="wrapper">
  <% flash.each do |key, value| -%>
    <div class="alert alert-<%=key%> alert-dismissable">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <%=h value %>
    </div>
  <% end %>
</div>
<div class="header">
  <h1>Welcome to Rightnowagram</h1>
  <h5>Post your photos. Like right now!</h5>
</div>
<div class="welcome-page">
</div>