config/routes.rb
Rails.application.routes.draw do

  resources :users, controller: "users" do
    resources :likes, controller: "likes"
    resources :posts, controller: "posts"
    resources :comments, controller: "comments"
  end

  resources :posts, controller: "posts" do
    resources :comments, controller: "comments", only: [:create, :new, :update, :destroy]
    resources :likes, controller: "likes"
    resources :buyings, controller: "buyings"
  end

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: 'logout'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/posts/payment/new" => "payment#new", as: "payment_new"
  post '/posts/payment/checkout' => "payment#checkout", as: "payment_checkout"
  root 'welcome#index'
end

app/models/buying.rb
class Buying < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_presence_of :address
end

app/controllers/buyings_controller.rb
class BuyingsController < ApplicationController
  def new
  end

  def create
    @post = Post.find(params[:post_id])
    @buying = current_user.buyings.new(buying_params)
    @buying.post = @post

    if @buying.save
      redirect_to post_buying_path(@post,@buying)
    else
      flash[:danger] = "Something seems to be wrong"
      render :new
    end
  end

  def show
    @buying = Buying.find(params[:id])
  end



  private

  def buying_params
    params.require(:buying).permit(:address)
  end
end

app/helpers/buyings_helper.rb
module BuyingsHelper
end

app/views/buyings/_form.html.erb
<%= form_for [@post, @buying] do |form| %>
  <%= form.hidden_field :post_id, value: @post.id %>
  <div>
    <%= form.label :address %>
    <%= form.text_field :address%>
  </div>
  <%= form.submit "Submit" %>
<%end%>

app/views/buyings/show.html.erb
<nav class="navbar">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand"><%= link_to "Rightnowagram", posts_path%></div>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.fullname %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= image_tag current_user.avatar.profile%></li>
            <li><%= link_to "Profile", user_path(current_user.id) %></li>
            <li><%= link_to "Search for Users", users_path%></li>
            <li><%= link_to "Log Out", logout_path%></li>
          </ul>
        </li>
      </ul>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</div>
<!-- /.container-fluid -->
</nav>
</div>
<div class = "text-center well">
  <h3>Total Amount:</h3>
  $<%= @buying.post.price%><br>
  <h3>Address</h3>
  <%= @buying.address%><br>
  <%= link_to "Buy Image", payment_new_path, class: "btn btn-default" %><br>
</div>