config/routes.rb
Rails.application.routes.draw do

  resources :users, controller: "users" do
    resources :likes, controller: "likes"
    resources :posts, controller: "posts"
    resources :comments, controller: "comments"
  end

  resources :posts, controller: "posts" do
    resources :comments, controller: "comments", only: [:create, :new, :update, :destroy]
    resources :likes, controller: "likes"
    resources :buyings, controller: "buyings"
  end

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: 'logout'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/posts/payment/new" => "payment#new", as: "payment_new"
  post '/posts/payment/checkout' => "payment#checkout", as: "payment_checkout"
  root 'welcome#index'
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploaders :images, ImagesUploader
  belongs_to :user
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :buyings

  validates_presence_of :images
  validates_presence_of :price

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order("created_at DESC")
    @comment = Comment.new
    @user = User.new
  end


  def new
    @post = Post.new
  end

  def create
    @post = Post.new(create_params)
    @post.user_id = current_user.id
    @post.time = Time.now
    if @post.save
      flash[:success] = "Post has been created."
      redirect_to post_path(@post)
    else
      flash.now[:danger] = "There's seem to be an error."
      render :new

    end
  end

  def show
    @buying = Buying.new
  end

  def edit
  end

  def update
    @post.update(update_params)
    if @post.save
      flash[:success] = "Updated."
      redirect_to @post
    else
      flash.now[:danger] = "Update fail."
      render :edit
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private

  def create_params
    params.require(:post).permit(:caption, :price, {images: []})
  end

  def update_params
    params.require(:post).permit(:caption)
  end


  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<nav class="navbar">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand"><%= link_to "Rightnowagram", posts_path%></div>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Log Out", logout_path%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.fullname %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= image_tag current_user.avatar.profile%></li>
            <li><%= link_to "Profile", user_path(current_user.id) %></li>
            <li><%= link_to "Edit Profile", edit_user_path(current_user.id)%></li>
            <li><%= link_to "Search for Users", users_path%></li>
          </ul>
        </li>
      </ul>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</div>
<!-- /.container-fluid -->
</nav>
</div>
<h1>Editing Post</h1>
<%= form_for @post do |post| %>
  <%= post.text_field :caption %>
  <%= post.submit "Submit"%>
<%end%>
<%= link_to 'Delete', post_path(@post.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
<%= link_to 'Back', post_path(@post.id), class: "btn btn-default" %>

app/views/posts/index.html.erb
<nav class="navbar">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand"><%= link_to "Rightnowagram", posts_path%></div>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.fullname %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= image_tag current_user.avatar.profile%></li>
            <li><%= link_to "Profile", user_path(current_user.id) %></li>
            <li><%= link_to "Search for Users", users_path%></li>
            <li><%= link_to "Log Out", logout_path%></li>
          </ul>
        </li>
      </ul>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</div>
<!-- /.container-fluid -->
</nav>
</div>
<p id="notice"><%= notice %></p>
<div class="wrapper">
  <% flash.each do |key, value| -%>
    <div class="alert alert-<%=key%> alert-dismissable">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <%=h value %>
    </div>
  <% end %>
</div>
<h1>Posts</h1>
<div class = "col-sm-2"></div>
<div class = "col-sm-8 well">
  <br>
  <%=link_to "Upload New Image", new_post_path, class: "upload-link btn btn-primary" %><br>
  <% @posts.each do |post|%><br>
    <div class = "image-details">
      <b><%= link_to post.user.fullname, user_path(post.user_id) %></b><br>
      <%= time_ago_in_words(post.time) unless post.time.blank?%>&nbsp;
      <%= link_to "Go to Post", post_path(post.id) %><br>
    </div>
    <div class = "text-center">
      <%= image_tag post.images[0].display.url if post.images[0]%><br>
    </div>
    <div class = "image-details">
      <span class="likes_count"> <%= post.likes.count %> </span> <span class="likes-word"><%= 'like'.pluralize(post.likes.count) %></span>
      <%= link_to post_likes_path(post), class: 'likes-link' do %>
        Like<br>
      <% end %>
      <%= post.caption %><br>
      <% post.comments.each do |comment|%>
        <strong><%= link_to comment.user.fullname, user_path(comment.user_id)%></strong>&nbsp;<%= comment.contents%><br>
      <%end%>
      <%= form_for [post, @comment] do |form| %>
        <%= form.text_area :contents, placeholder: "Add a comment...", id: 'new-comment-text' %>
        <%= form.submit "Submit", class: 'submit-comment-button' %>
      <%end%>
    </div>
  <%end%>
</div>
<div class = "col-sm-2"></div>

app/views/posts/new.html.erb
<nav class="navbar">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand"><%= link_to "Rightnowagram", posts_path%></div>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.fullname %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= image_tag current_user.avatar.profile%></li>
            <li><%= link_to "Profile", user_path(current_user.id) %></li>
            <li><%= link_to "Search for Users", users_path%></li>
            <li><%= link_to "Log Out", logout_path%></li>
          </ul>
        </li>
      </ul>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</div>
<!-- /.container-fluid -->
</nav>
<h1>New Post</h1>
<%= form_for @post, html: { multipart: true } do |post| %>
  <%= post.label "Select Image", class: "select-image-label" %>
  <%= post.file_field :images, multiple: true, onchange: "previewImage(event)", id: "new-image" %>
  <%= post.text_field :caption, placeholder: "Enter caption", id: "post-caption" %>
  <%= post.number_field :price, placeholder: "Place a price.."%>
  <%= post.submit "Post Image", class: "new-post-submit-button" %>
<% end %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<nav class="navbar">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand"><%= link_to "Rightnowagram", posts_path%></div>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.fullname %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= image_tag current_user.avatar.profile%></li>
            <li><%= link_to "Profile", user_path(current_user.id) %></li>
            <li><%= link_to "Search for Users", users_path%></li>
            <li><%= link_to "Log Out", logout_path%></li>
          </ul>
        </li>
      </ul>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</div>
<!-- /.container-fluid -->
</nav>
</div>
<p id="notice"><%= notice %></p>
<br>
<div class = "container text-center">
  $<%=@post.price%><br>
  <%= time_ago_in_words(@post.time) unless @post.time.blank?%><br>
  <%= image_tag @post.images[0].display.url %><br>
  <div class = "image-details">
    <span class="likes_count"> <%= @post.likes.count %> </span> <span class="likes-word"><%= 'like'.pluralize(@post.likes.count) %></span>
    <%= link_to post_likes_path(@post), class: 'likes-link' do %>
      Like<br>
    <%end%>
    <%= @post.caption %><br>
    <% @post.comments.each do |comment| %>
      <b><%= comment.user.fullname %></b>
      <%= comment.contents %><br>
    <%end%>
    <% if current_user.id == @post.user_id%>
      <%= link_to "Edit caption", edit_post_path, class: "btn btn-default" %>
    <%else%>
      <hr>
      <b> Enter address to buy this image </b>
      <%= render 'buyings/form'%>
    <%end%>
  </div>
  <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-default" %>
  <%= link_to 'Back', posts_path, class: "btn btn-default" %>